version: 2.1

jobs:
  build-image:
    machine:
      image: ubuntu-2204:2023.04.2
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_ACCESS_TOKEN" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build (and maybe push) multi-arch images
          command: |
            docker buildx create --use
            TAG_NAME=$(date +%Y-%m-%d-%H-%M-%S)
            docker buildx build --platform linux/amd64,linux/arm64 \
              --file Dockerfile \
              --tag $DOCKERHUB_USERNAME/datatools-ui:${TAG_NAME} \
              --build-arg GRAPH_HOPPER_URL=${GRAPH_HOPPER_URL} \
              --build-arg AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID} \
              --build-arg AUTH0_DOMAIN=${AUTH0_DOMAIN} \
              --build-arg MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN} \
              --build-arg GRAPH_HOPPER_KEY=${GRAPH_HOPPER_KEY} \
              $(if [ "$CIRCLE_BRANCH" = "dev" ]; then echo '--push'; fi) .

workflows:
  my-workflow:
    jobs:
      - build-image:
          context:
            - docker-hub
            - datatools
